### ISSUE TITLE
Some problem

### ISSUE THREAD

**Issue by pilgrimygy** [JuliaPOMDP/POMDPs.jl#311] opened 2020-07-13 11:21 UTC
When I run the code：
```
using LaserTag
using POMDPGifs
using QMDP
using Random
using ParticleFilters

rng = MersenneTwister(7)

m = gen_lasertag(rng=rng, robot_position_known=true)
policy = solve(QMDPSolver(verbose=true), m)
filter = SIRParticleFilter(m, 10000, rng=rng)

@show makegif(m, policy, filter, filename="out.gif", rng=rng)
```

I encountered this problem, and I can't solve it. Could you give me a hand?

```
!LuaTeX error (file C:/CTEX/CTeX/fonts/sfd/Unicode.sfd): invalid range:
_0xFFFF

 ==> Fatal error occurred, no output PDF file produced!

ERROR: LoadError: LaTeX error
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] (::TikzPictures.var"#6#7"{TikzPictures.PDF,TikzPictures.TikzPicture,String})() at C:\Users\pilgrim\.juliapro\JuliaPro_v1.4.2-1\packages\TikzPictures\QJ62d\src\TikzPictures.jl:264
 [3] cd(::TikzPictures.var"#6#7"{TikzPictures.PDF,TikzPictures.TikzPicture,String}, ::String) at .\file.jl:93
 [4] save(::TikzPictures.PDF, ::TikzPictures.TikzPicture) at C:\Users\pilgrim\.juliapro\JuliaPro_v1.4.2-1\packages\TikzPictures\QJ62d\src\TikzPictures.jl:208
 [5] show(::IOStream, ::MIME{Symbol("image/png")}, ::LaserTagVis) at C:\Users\pilgrim\.juliapro\JuliaPro_v1.4.2-1\packages\LaserTag\rRla5\src\visualization.jl:29
 [6] writeframe(::String, ::MIME{Symbol("image/png")}, ::LaserTagVis) at C:\Users\pilgrim\.juliapro\JuliaPro_v1.4.2-1\packages\Reel\Mu9ck\src\Reel.jl:35
 [7] push! at C:\Users\pilgrim\.juliapro\JuliaPro_v1.4.2-1\packages\Reel\Mu9ck\src\Reel.jl:42 [inlined]
 [8] macro expansion at C:\Users\pilgrim\.juliapro\JuliaPro_v1.4.2-1\packages\POMDPGifs\NifU5\src\POMDPGifs.jl:120 [inlined]
 [9] macro expansion at C:\Users\pilgrim\.juliapro\JuliaPro_v1.4.2-1\packages\ProgressMeter\N86Uo\src\ProgressMeter.jl:732 [inlined]
 [10] makegif(::LaserTagPOMDP{DESPOTEmu,StaticArrays.MArray{Tuple{8},Int64,1,8}}, ::POMDPSimulators.SimHistory{NamedTuple{(:s, :a, :sp, :o, :r, :t, :action_info, :b, :bp, :update_info),Tuple{LTState,Int64,LTState,StaticArrays.MArray{Tuple{8},Int64,1,8},Float64,Int64,Nothing,ParticleCollection{LTState},ParticleCollection{LTState},Nothing}}}; filename::String, spec::Nothing, show_progress::Bool, render_kwargs::NamedTuple{(),Tuple{}}, fps::Int64) at C:\Users\pilgrim\.juliapro\JuliaPro_v1.4.2-1\packages\POMDPGifs\NifU5\src\POMDPGifs.jl:119
 [11] simulate(::GifSimulator, ::LaserTagPOMDP{DESPOTEmu,StaticArrays.MArray{Tuple{8},Int64,1,8}}, ::POMDPPolicies.AlphaVectorPolicy{LaserTagPOMDP{DESPOTEmu,StaticArrays.MArray{Tuple{8},Int64,1,8}},Int64}, ::BasicParticleFilter{LaserTagPOMDP{DESPOTEmu,StaticArrays.MArray{Tuple{8},Int64,1,8}},LaserTagPOMDP{DESPOTEmu,StaticArrays.MArray{Tuple{8},Int64,1,8}},LowVarianceResampler,MersenneTwister,Array{LTState,1}}) at C:\Users\pilgrim\.juliapro\JuliaPro_v1.4.2-1\packages\POMDPGifs\NifU5\src\POMDPGifs.jl:57
 [12] #makegif#4 at C:\Users\pilgrim\.juliapro\JuliaPro_v1.4.2-1\packages\POMDPGifs\NifU5\src\POMDPGifs.jl:83 [inlined]
 [13] top-level scope at show.jl:613
in expression starting at untitled-c1282b29e8afbf0a83499fea45c36a74:13
```

**Comment by zsunberg** [comment] 2020-07-15 16:13
@pilgrimygy thanks for reporting!

Duplicate of JuliaPOMDP/LaserTag.jl#3 see there for discussion

**Closed by zsunberg** 2020-07-15 16:13 UTC
